trytest/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace trytest.Models
{
    public class User
    {
        public int UserID { get; set; }


        public string UserName { get; set; }


        public string UserNickname { get; set; }


        public string UserPassword { get; set; }

        public string UserEmail { get; set; }
        public int UserAge { get; set; }
        public string UserSex { get; set; }

        public int UserRoleID { get; set; }
        public virtual  UserRole userrole {get;set;}

    }
}

trytest/Controllers/EventInProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trytest.Models;

namespace trytest.Controllers
{
    public class EventInProjectController : Controller
    {
        private Dbtest db = new Dbtest();

        //
        // GET: /EventInProject/

        public ActionResult Index()
        {
            //EventInProjectType type = new EventInProjectType();
            //EventInProjectStatus eventrole0 = new EventInProjectStatus();
            var type = from t in db.EventInProjcetTypeTable where t.EventInProjectTypeID == 1 select t;

            var status = from s in db.EventInProjcetStatusTable where s.EventInProjectStatusID == 1 select s;

            if (status.Count() == 0)
            {
                EventInProjectStatus eventrole1 = new EventInProjectStatus();
                eventrole1.EventInProjectStatusID = 1;
                eventrole1.EventInProjectStatusName = "Open";
                EventInProjectStatus eventrole2 = new EventInProjectStatus();
                eventrole2.EventInProjectStatusID = 2;
                eventrole2.EventInProjectStatusName = "Pending";
                EventInProjectStatus eventrole3 = new EventInProjectStatus();
                eventrole3.EventInProjectStatusID = 3;
                eventrole3.EventInProjectStatusName = "Closed";
                EventInProjectStatus eventrole4 = new EventInProjectStatus();
                eventrole4.EventInProjectStatusID = 4;
                eventrole4.EventInProjectStatusName = "Lock";
                db.EventInProjcetStatusTable.Add(eventrole1);
                db.EventInProjcetStatusTable.Add(eventrole2);
                db.EventInProjcetStatusTable.Add(eventrole3);
                db.EventInProjcetStatusTable.Add(eventrole4);
                db.SaveChanges();
            }
            if (type.Count() == 0)
            {
                EventInProjectType type1 = new EventInProjectType();
                type1.EventInProjectTypeID = 1;
                type1.EventInProjectTypeName = "Breakfast";
                EventInProjectType type2 = new EventInProjectType();
                type2.EventInProjectTypeID = 2;
                type2.EventInProjectTypeName = "Lunch";
                EventInProjectType type3 = new EventInProjectType();
                type3.EventInProjectTypeID = 3;
                type3.EventInProjectTypeName = "Dinner";
                EventInProjectType type4 = new EventInProjectType();
                type4.EventInProjectTypeID = 4;
                type4.EventInProjectTypeName = "Party";
                EventInProjectType type5 = new EventInProjectType();
                type5.EventInProjectTypeID = 5;
                type5.EventInProjectTypeName = "Doing Sports";
                EventInProjectType type6 = new EventInProjectType();
                type6.EventInProjectTypeID = 6;
                type6.EventInProjectTypeName = "Play games";
                db.EventInProjcetTypeTable.Add(type1);
                db.EventInProjcetTypeTable.Add(type2);
                db.EventInProjcetTypeTable.Add(type3);
                db.EventInProjcetTypeTable.Add(type4);
                db.EventInProjcetTypeTable.Add(type5);
                db.EventInProjcetTypeTable.Add(type6);
                db.SaveChanges();
            }
            var eventinprojcettable = db.EventInProjcetTable.Include(e => e.friend).Include(e => e.eventinprojecttype).Include(e => e.eventinprojectstatus);
            return View(eventinprojcettable.ToList());
        }

        //
        // GET: /EventInProject/Details/5

        public ActionResult Details(int id = 0)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            if (eventinproject == null)
            {
                return HttpNotFound();
            }
            return View(eventinproject);
        }

        //
        // GET: /EventInProject/Create

        public ActionResult Create()
        {
            
            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName");
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName");
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName");
            return View();
        }

        //
        // POST: /EventInProject/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventInProject eventinproject)
        {


            if (ModelState.IsValid)
            {
                if( int.Parse(Session["UserRole"].ToString())==3)
                { eventinproject.EventInProjectStatusID = 2; }

                db.EventInProjcetTable.Add(eventinproject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName", eventinproject.FriendID);
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName", eventinproject.EventInProjectTypeID);
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName", eventinproject.EventInProjectStatusID);
            return View(eventinproject);
        }

        //
        // GET: /EventInProject/Edit/5

        public ActionResult Edit(int id = 0)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            if (eventinproject == null)
            {
                return HttpNotFound();
            }
            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName", eventinproject.FriendID);
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName", eventinproject.EventInProjectTypeID);
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName", eventinproject.EventInProjectStatusID);
            return View(eventinproject);
        }

        //
        // POST: /EventInProject/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EventInProject eventinproject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventinproject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName", eventinproject.FriendID);
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName", eventinproject.EventInProjectTypeID);
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName", eventinproject.EventInProjectStatusID);
            return View(eventinproject);
        }

        //
        // GET: /EventInProject/Delete/5

        public ActionResult Delete(int id = 0)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            if (eventinproject == null)
            {
                return HttpNotFound();
            }
            return View(eventinproject);
        }

        //
        // POST: /EventInProject/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            db.EventInProjcetTable.Remove(eventinproject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

trytest/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trytest.Models;

namespace trytest.Controllers
{
    public class FriendController : Controller
    {
        private Dbtest db = new Dbtest();

        //
        // GET: /Friend/

      
        public ActionResult Index()
        {
            return View(db.FriendTable.ToList());
        }
        public ActionResult Navigate()
        {
            return View();
        }

        //
        // GET: /Friend/Details/5

        public ActionResult Details(int id = 0)
        {
            Friend friend = db.FriendTable.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            return View(friend);
        }

        //
        // GET: /Friend/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Friend/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Friend friend)
        {
            if (ModelState.IsValid)
            {
                db.FriendTable.Add(friend);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(friend);
        }

        //
        // GET: /Friend/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Friend friend = db.FriendTable.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            return View(friend);
        }

        //
        // POST: /Friend/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Friend friend)
        {
            if (ModelState.IsValid)
            {
                db.Entry(friend).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(friend);
        }

        //
        // GET: /Friend/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Friend friend = db.FriendTable.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            return View(friend);
        }

        //
        // POST: /Friend/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Friend friend = db.FriendTable.Find(id);
            db.FriendTable.Remove(friend);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

trytest/Views/User/Create.cshtml
@model trytest.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>User</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserNickname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserNickname)
            @Html.ValidationMessageFor(model => model.UserNickname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserPassword)
            @Html.ValidationMessageFor(model => model.UserPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserEmail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserEmail)
            @Html.ValidationMessageFor(model => model.UserEmail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserAge)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserAge)
            @Html.ValidationMessageFor(model => model.UserAge)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserSex)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserSex)
            @Html.ValidationMessageFor(model => model.UserSex)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

trytest/Views/User/Delete.cshtml
@model trytest.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>User</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserNickname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserNickname)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserPassword)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserPassword)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserEmail)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserEmail)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserAge)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserAge)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserSex)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserSex)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

trytest/Views/User/Details.cshtml
@model trytest.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>User</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserNickname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserNickname)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserPassword)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserPassword)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserEmail)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserEmail)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserAge)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserAge)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserSex)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserSex)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.UserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

trytest/Views/User/Edit.cshtml
@model trytest.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>User</legend>

        @Html.HiddenFor(model => model.UserID)

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserNickname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserNickname)
            @Html.ValidationMessageFor(model => model.UserNickname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserPassword)
            @Html.ValidationMessageFor(model => model.UserPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserEmail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserEmail)
            @Html.ValidationMessageFor(model => model.UserEmail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserAge)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserAge)
            @Html.ValidationMessageFor(model => model.UserAge)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserSex)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserSex)
            @Html.ValidationMessageFor(model => model.UserSex)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

trytest/Views/User/FindFriend.cshtml
@model trytest.Models.User

@{
    ViewBag.Title = "FindFriend";
}

<h2>please input the friend name which you want to find</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

 @Html.ValidationSummary(true)
        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>
        <p>
            <input type="submit" value="search" />
        </p>
       
}

trytest/Views/User/Index.cshtml
@model IEnumerable<trytest.Models.User>

@{
    ViewBag.Title = "Index";
}

<h2>Index in User</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserNickname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserAge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserSex)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserNickname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserPassword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserAge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserSex)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserID }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserID })  |  
            @Html.ActionLink("Add to your friend", "AddFriend","User", new { id = item.UserID },null)
        </td>
    </tr>
}

</table>
 
<p> @Html.ActionLink("Back to Navigate Page", "Navigate")</p>
<p> @Html.ActionLink("Search user by name", "FindFriend")</p>

trytest/Views/User/Login.cshtml
@model trytest.Models.User

@{
    ViewBag.Title = "Login";
}

<h2>Login in User</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>User Logon</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserPassword)
        </div>
        <div class="editor-field">

            @Html.PasswordFor(model => model.UserPassword)

            @Html.ValidationMessageFor(model => model.UserPassword)
        </div>

        <p>
            <input type="submit" value="Login" />
            <input type="button" value="Register" onclick="window.location.href='/User/Create'" />
        </p>
    </fieldset>
     
    
}

trytest/Views/User/Navigate.cshtml
@{
    ViewBag.Title = "NavigatePage";
}

<h2>NavigatePage</h2>
<div>
   <h1> @Html.ActionLink("Account Management", "Edit", "User", new { id = int.Parse(Session["SessionID"].ToString()) }, null)</h1>
   <h1> @Html.ActionLink("Event Management", "Index", "EventInProject")</h1>
    <h1> @Html.ActionLink("Friend Management", "Index", "Friend")</h1>
 @if( int.Parse(Session["UserRole"].ToString())==1)
  {  
    <h1> @Html.ActionLink("User Management", "Index", "User")</h1>

  }
</div>

trytest/Views/User/ShowCertainUser.cshtml
@model IEnumerable<trytest.Models.User>

@{
    ViewBag.Title = "ShowCertainUser";
}

<h2>ShowCertainUser</h2>>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserNickname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserAge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserSex)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserNickname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserPassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserAge)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserSex)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UserID }) |
                @Html.ActionLink("Details", "Details", new { id = item.UserID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UserID })  |
                @Html.ActionLink("Add to your friend", "AddFriend", "User", new { id = item.UserID }, null)
            </td>
        </tr>
    }

</table>

<p> @Html.ActionLink("Back to Navigate Page", "Navigate")</p>
<p> @Html.ActionLink("Search user by name", "FindFriend")</p>