trytest/Models/EventInProject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace trytest.Models
{
    public class EventInProject
    
    {
          public int EventInProjectID { get; set; }
        [Required]
        public string EventName { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Description { get; set; }
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [DataType(DataType.Time)]
        public string Time { get; set; }

        public int FriendID { get; set; }
        public virtual Friend friend { get; set; }

        public int EventInProjectTypeID { get; set; }
        public virtual EventInProjectType eventinprojecttype { get; set; }

        public int EventInProjectStatusID { get; set; }
        public virtual EventInProjectStatus eventinprojectstatus { get; set; }
        

        //public int ActivityTypeID { get; set; }
        //public virtual ActivityType ActivityType { get; set; }

        //public int ActivityStatusID { get; set; }
        //public virtual ActivityStatus ActivityStatus { get; set; }

        //public int PersonID { get; set; }
        //public string PersonName { get; set; }
    }
}

trytest/Models/EventInProjectType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace trytest.Models
{
    public class EventInProjectType
    {
        public int EventInProjectTypeID { get; set; }
        public string EventInProjectTypeName { get; set; }
    }
}

trytest/Controllers/ContributionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trytest.Models;

namespace trytest.Controllers
{
    public class ContributionController : Controller
    {
        private Dbtest db = new Dbtest();

        //
        // GET: /Contribution/

        public ActionResult Index()
        {

            var con0 = from c in db.ContributionTypeTable where c.ContributionTypeID == 1 select c;

            if (con0.Count() == 0)
            {
                ContributionType con1 = new ContributionType();
                con1.ContributionTypeID = 1;
                con1.ContributionTypeName = "Money";
                ContributionType con2 = new ContributionType();
                con2.ContributionTypeID = 2;
                con2.ContributionTypeName = "Food";
                ContributionType con3 = new ContributionType();
                con3.ContributionTypeID = 3;
                con3.ContributionTypeName = "Beverage";
                ContributionType con4 = new ContributionType();
                con4.ContributionTypeID = 4;
                con4.ContributionTypeName = "Else";
                
                db.ContributionTypeTable.Add(con1);
                db.ContributionTypeTable.Add(con2);
                db.ContributionTypeTable.Add(con3);
                db.ContributionTypeTable.Add(con4);
              
                db.SaveChanges();
            }

            var contributiontable = db.ContributionTable.Include(c => c.contributiontype);
            return View(contributiontable.ToList());
        }

        //
        // GET: /Contribution/Details/5

        public ActionResult Details(int id = 0)
        {
            Contribution contribution = db.ContributionTable.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // GET: /Contribution/Create

        public ActionResult Create()
        {
            ViewBag.ContributionTypeID = new SelectList(db.ContributionTypeTable, "ContributionTypeID", "ContributionTypeName");
            return View();
        }

        //
        // POST: /Contribution/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                db.ContributionTable.Add(contribution);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ContributionTypeID = new SelectList(db.ContributionTypeTable, "ContributionTypeID", "ContributionTypeName", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // GET: /Contribution/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Contribution contribution = db.ContributionTable.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContributionTypeID = new SelectList(db.ContributionTypeTable, "ContributionTypeID", "ContributionTypeName", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // POST: /Contribution/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contribution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContributionTypeID = new SelectList(db.ContributionTypeTable, "ContributionTypeID", "ContributionTypeName", contribution.ContributionTypeID);
            return View(contribution);
        }

        //
        // GET: /Contribution/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Contribution contribution = db.ContributionTable.Find(id);
            if (contribution == null)
            {
                return HttpNotFound();
            }
            return View(contribution);
        }

        //
        // POST: /Contribution/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contribution contribution = db.ContributionTable.Find(id);
            db.ContributionTable.Remove(contribution);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

trytest/Controllers/EventInProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trytest.Models;

namespace trytest.Controllers
{
    public class EventInProjectController : Controller
    {
        private Dbtest db = new Dbtest();

        //
        // GET: /EventInProject/

        public ActionResult Index()
        {
            //EventInProjectType type = new EventInProjectType();
            //EventInProjectStatus eventrole0 = new EventInProjectStatus();
            var type = from t in db.EventInProjcetTypeTable where t.EventInProjectTypeID == 1 select t;

            var status = from s in db.EventInProjcetStatusTable where s.EventInProjectStatusID == 1 select s;

            if (status.Count() == 0)
            {
                EventInProjectStatus eventrole1 = new EventInProjectStatus();
                eventrole1.EventInProjectStatusID = 1;
                eventrole1.EventInProjectStatusName = "Open";
                EventInProjectStatus eventrole2 = new EventInProjectStatus();
                eventrole2.EventInProjectStatusID = 2;
                eventrole2.EventInProjectStatusName = "Pending";
                EventInProjectStatus eventrole3 = new EventInProjectStatus();
                eventrole3.EventInProjectStatusID = 3;
                eventrole3.EventInProjectStatusName = "Closed";
                EventInProjectStatus eventrole4 = new EventInProjectStatus();
                eventrole4.EventInProjectStatusID = 4;
                eventrole4.EventInProjectStatusName = "Lock";
                db.EventInProjcetStatusTable.Add(eventrole1);
                db.EventInProjcetStatusTable.Add(eventrole2);
                db.EventInProjcetStatusTable.Add(eventrole3);
                db.EventInProjcetStatusTable.Add(eventrole4);
                db.SaveChanges();
            }
            if (type.Count() == 0)
            {
                EventInProjectType type1 = new EventInProjectType();
                type1.EventInProjectTypeID = 1;
                type1.EventInProjectTypeName = "Breakfast";
                EventInProjectType type2 = new EventInProjectType();
                type2.EventInProjectTypeID = 2;
                type2.EventInProjectTypeName = "Lunch";
                EventInProjectType type3 = new EventInProjectType();
                type3.EventInProjectTypeID = 3;
                type3.EventInProjectTypeName = "Dinner";
                EventInProjectType type4 = new EventInProjectType();
                type4.EventInProjectTypeID = 4;
                type4.EventInProjectTypeName = "Party";
                EventInProjectType type5 = new EventInProjectType();
                type5.EventInProjectTypeID = 5;
                type5.EventInProjectTypeName = "Doing Sports";
                EventInProjectType type6 = new EventInProjectType();
                type6.EventInProjectTypeID = 6;
                type6.EventInProjectTypeName = "Play games";
                db.EventInProjcetTypeTable.Add(type1);
                db.EventInProjcetTypeTable.Add(type2);
                db.EventInProjcetTypeTable.Add(type3);
                db.EventInProjcetTypeTable.Add(type4);
                db.EventInProjcetTypeTable.Add(type5);
                db.EventInProjcetTypeTable.Add(type6);
                db.SaveChanges();
            }
            var eventinprojcettable = db.EventInProjcetTable.Include(e => e.friend).Include(e => e.eventinprojecttype).Include(e => e.eventinprojectstatus);
            return View(eventinprojcettable.ToList());
        }

        //
        // GET: /EventInProject/Details/5

        public ActionResult Details(int id = 0)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            if (eventinproject == null)
            {
                return HttpNotFound();
            }
            return View(eventinproject);
        }

        //
        // GET: /EventInProject/Create

        public ActionResult Create()
        {
            
            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName");
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName");
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName");
            return View();
        }

        //
        // POST: /EventInProject/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventInProject eventinproject)
        {


            if (ModelState.IsValid)
            {
                if( int.Parse(Session["UserRole"].ToString())==3)
                { eventinproject.EventInProjectStatusID = 2; }

                db.EventInProjcetTable.Add(eventinproject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName", eventinproject.FriendID);
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName", eventinproject.EventInProjectTypeID);
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName", eventinproject.EventInProjectStatusID);
            return View(eventinproject);
        }

        //
        // GET: /EventInProject/Edit/5

        public ActionResult Edit(int id = 0)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            if (eventinproject == null)
            {
                return HttpNotFound();
            }
            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName", eventinproject.FriendID);
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName", eventinproject.EventInProjectTypeID);
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName", eventinproject.EventInProjectStatusID);
            return View(eventinproject);
        }

        //
        // POST: /EventInProject/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EventInProject eventinproject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventinproject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FriendID = new SelectList(db.FriendTable, "FriendID", "FriendName", eventinproject.FriendID);
            ViewBag.EventInProjectTypeID = new SelectList(db.EventInProjcetTypeTable, "EventInProjectTypeID", "EventInProjectTypeName", eventinproject.EventInProjectTypeID);
            ViewBag.EventInProjectStatusID = new SelectList(db.EventInProjcetStatusTable, "EventInProjectStatusID", "EventInProjectStatusName", eventinproject.EventInProjectStatusID);
            return View(eventinproject);
        }

        //
        // GET: /EventInProject/Delete/5

        public ActionResult Delete(int id = 0)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            if (eventinproject == null)
            {
                return HttpNotFound();
            }
            return View(eventinproject);
        }

        //
        // POST: /EventInProject/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventInProject eventinproject = db.EventInProjcetTable.Find(id);
            db.EventInProjcetTable.Remove(eventinproject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

trytest/Views/EventInProject/Create.cshtml
@model trytest.Models.EventInProject

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EventInProject</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.EventName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EventName)
            @Html.ValidationMessageFor(model => model.EventName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Time)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Time)
            @Html.ValidationMessageFor(model => model.Time)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FriendID, "friend")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FriendID", String.Empty)
            @Html.ValidationMessageFor(model => model.FriendID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EventInProjectTypeID, "eventinprojecttype")
        </div>
        <div class="editor-field">
            @Html.DropDownList("EventInProjectTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.EventInProjectTypeID)
        </div>
@if (int.Parse(Session["UserRole"].ToString()) == 1)
{      <div class="editor-label">
            @Html.LabelFor(model => model.EventInProjectStatusID, "eventinprojectstatus")
        </div>
        <div class="editor-field">
            @Html.DropDownList("EventInProjectStatusID", String.Empty)
            @Html.ValidationMessageFor(model => model.EventInProjectStatusID)
        </div>
}
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

trytest/Views/EventInProject/Delete.cshtml
@model trytest.Models.EventInProject

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>EventInProject</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EventName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EventName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Time)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Time)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.friend.FriendName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.friend.FriendName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.eventinprojecttype.EventInProjectTypeName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.eventinprojecttype.EventInProjectTypeName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.eventinprojectstatus.EventInProjectStatusName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.eventinprojectstatus.EventInProjectStatusName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

trytest/Views/EventInProject/Details.cshtml
@model trytest.Models.EventInProject

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>EventInProject</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EventName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EventName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Time)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Time)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.friend.FriendName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.friend.FriendName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.eventinprojecttype.EventInProjectTypeName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.eventinprojecttype.EventInProjectTypeName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.eventinprojectstatus.EventInProjectStatusName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.eventinprojectstatus.EventInProjectStatusName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.EventInProjectID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

trytest/Views/EventInProject/Edit.cshtml
@model trytest.Models.EventInProject

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EventInProject</legend>

        @Html.HiddenFor(model => model.EventInProjectID)

        <div class="editor-label">
            @Html.LabelFor(model => model.EventName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EventName)
            @Html.ValidationMessageFor(model => model.EventName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Time)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Time)
            @Html.ValidationMessageFor(model => model.Time)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FriendID, "friend")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FriendID", String.Empty)
            @Html.ValidationMessageFor(model => model.FriendID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EventInProjectTypeID, "eventinprojecttype")
        </div>
        <div class="editor-field">
            @Html.DropDownList("EventInProjectTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.EventInProjectTypeID)
        </div>
@if( int.Parse(Session["UserRole"].ToString())==1)
{       <div class="editor-label">
            @Html.LabelFor(model => model.EventInProjectStatusID, "eventinprojectstatus")
        </div>
        <div class="editor-field">
            @Html.DropDownList("EventInProjectStatusID", String.Empty)
            @Html.ValidationMessageFor(model => model.EventInProjectStatusID)
        </div>
}
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

trytest/Views/EventInProject/Index.cshtml
@model IEnumerable<trytest.Models.EventInProject>

@{
    ViewBag.Title = "Index";
}

<h2>Index in EventInProject</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.friend.FriendName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.eventinprojecttype.EventInProjectTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.eventinprojectstatus.EventInProjectStatusName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.friend.FriendName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.eventinprojecttype.EventInProjectTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.eventinprojectstatus.EventInProjectStatusName)
        </td>
        <td>
           @if(int.Parse(Session["UserRole"].ToString()) == 1)
          { @Html.ActionLink("Edit", "Edit", new { id=item.EventInProjectID }) } |
             @Html.ActionLink("Details", "Details", new { id=item.EventInProjectID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EventInProjectID })
           
        </td>
    </tr>
}

</table>
<div>
    @Html.ActionLink("go to find contribution", "Index", "Contribution")
</div>